// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgSeAGsDo-asx2JS1nTBiPZHhudBf7pGs',
    appId: '1:523170538704:web:dc22f064ef8524874b2ad5',
    messagingSenderId: '523170538704',
    projectId: 'squip-2c976',
    authDomain: 'squip-2c976.firebaseapp.com',
    storageBucket: 'squip-2c976.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFPsoe4An-mAJsSlzonYFNWStIiXD7GQ',
    appId: '1:523170538704:android:71f2454f88937c884b2ad5',
    messagingSenderId: '523170538704',
    projectId: 'squip-2c976',
    storageBucket: 'squip-2c976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD5TYZLmLHSLwkZt8W0CjlWFvuJaAlmuI',
    appId: '1:523170538704:ios:310dc69ad3a8d3704b2ad5',
    messagingSenderId: '523170538704',
    projectId: 'squip-2c976',
    storageBucket: 'squip-2c976.appspot.com',
    iosClientId: '523170538704-2ncldf4gnpdlke6m4gcn5qb50slboade.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
